{% set name = "bioformats2raw" %}
{% set version = "0.3.0-rc3" %}
{% set tag = "v0.3.0rc3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

build:
  number: 0

source:
  url: https://github.com/glencoesoftware/{{ name }}/releases/download/v{{ tag }}/{{ name }}-{{ version }}.zip
  sha256: 96a6d4a584f14f8d17d561b11ffb0059c34d47e4c3ffcdca1d15685fc5f6374d
  patches:
    - windows-bat-classpath-wildcard.patch  # [win]

requirements:
  build:
    - m2-patch  # [win]
  run:
    - bioformats2raw-libs={{ PKG_VERSION }}-{{ PKG_BUILDNUM }}
    - openjdk

test:
  commands:
    - bioformats2raw a.fake output
    - bioformats2raw --file_type=zarr -r 2 a.fake output.zarr

extra:
  recipe-maintainers:
    - ome

about:
  home: https://www.openmicroscopy.org/
  license: GNU General Public v2 or later (GPLv2+)
  license_family: GPL2
  summary: Bio-Formats image file format to raw format converter
  dev_url: https://github.com/glencoesoftware/bioformats2raw/
