{% set name = "bioformats2raw-libs" %}
{% set version = "0.3.0-rc3" %}
{% set tag = "v0.3.0rc3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

build:
  number: 0
  noarch: generic

source:
  url: https://github.com/glencoesoftware/bioformats2raw/releases/download/v{{ tag }}/bioformats2raw-{{ version }}.zip
  sha256: 96a6d4a584f14f8d17d561b11ffb0059c34d47e4c3ffcdca1d15685fc5f6374d

# Leave the OS specific dependencies to the wrapper
requirements:
  run:
    - blosc

extra:
  recipe-maintainers:
    - ome

about:
  home: https://www.openmicroscopy.org/
  license: GNU General Public v2 or later (GPLv2+)
  license_family: GPL2
  summary: Bio-Formats image file format to raw format converter jars
  dev_url: https://github.com/glencoesoftware/bioformats2raw/
