{% set name = "bioformats2raw-libs" %}
{% set version = "0.2.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

build:
  number: 0
  noarch: generic

source:
  url: https://github.com/glencoesoftware/bioformats2raw/releases/download/v{{ version }}/bioformats2raw-{{ version }}.zip
  sha256: 3845453e495f118783d13122eba8a3997a45bef82ac4f08c711b8deae22ef8b2

# Leave the OS specific dependencies to the wrapper
requirements:
  run:
    - blosc

extra:
  recipe-maintainers:
    - ome

about:
  home: https://www.openmicroscopy.org/
  license: GNU General Public v2 or later (GPLv2+)
  license_family: GPL2
  summary: Bio-Formats image file format to raw format converter jars
  dev_url: https://github.com/glencoesoftware/bioformats2raw/
